make:
	javac application/*.java
teams01: 
	java application.Main teams01.txt > teams01.log
teams02: 
	java application.Main teams02.txt > teams02.log
teams04: 
	java application.Main teams04.txt > teams04.log
teams08: 
	java application.Main teams08.txt > teams08.log
teams16: 
	java application.Main teams16.txt > teams16.log
teams32: 
	java application.Main teams32.txt > teams32.log
clean:
	\rm application/*.class